url: drewfrom.space
baseurl:

# Site settings
title: Drew Price
email: drew.s.price@gmail.com
description: "My name is Drew. I build things for the web."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: '545454'
  secondary: '707070'
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/drewfromspace
  - title: github
    url: http://github.com/drewprice
  - title: codepen
    url: http://codepen.io/drewprice/
  - title: linkedin
    url: http://www.linkedin.com/in/drewscottprice
  - title: instagram
    url: http://instagram.com/drewfromspace/

# Build settings
markdown: redcarpet
permalink: pretty
